### ISSUE TITLE
View is moved if switching windows when cursor is far right

### ISSUE THREAD

**Issue by skeate** [roman/golden-ratio#19] opened 2014-07-13 15:07 UTC
Made a gif to be clear:

![Imgur](http://i.imgur.com/EcRFW9d.gif)

When the cursor is on the 'z' and the window is toggled back and forth, the view changes. I've gotten around this with `autocmd WinEnter * :normal ze`, but there's probably a better way.

**Comment by idbrii** [comment] 2016-12-17 21:00
I think what you're describing is:

A is visible.
Position cursor on z.
Window switch.
Golden ratio autocmd resizes windows to make first window smaller. Since doing so makes z not visible so view shifts to make z (previous cursor position) visible.
You want A to remain visible. Is that right?

If you disable golden ratio, do the same thing, but use a `10 wincmd +` to increase size of second window, what happens?

**Comment by skeate** [comment] 2016-12-19 15:19
> Golden ratio autocmd resizes windows to make first window smaller. Since doing so makes z not visible so view shifts to make z (previous cursor position) visible.
> You want A to remain visible. Is that right?

No. z should remain visible in this case; the problem is the switch _back_.

Apparently my gif is actually just confusing things, rather than helping to make it clear. 😢 

1. Open two windows, the left of which has a long-ish line. Specifically, long enough that with golden-ratio, the shrunken size is longer than the window is wide, but short enough that the expanded size can fit the whole thing.
2. Go to the end of that long line (should still see beginning of line in window)
3. Switch to right window. The left window shrinks, cutting off the first part of the line.
4. Switch to the left window. The text doesn't move; you can't see the beginning of the line, even though there's room for it.

**Comment by idbrii** [comment] 2017-01-11 00:25
I think this is native vim behavior.

If you turn off golden-ratio and use `vert resize 30` before switching windows, the beginning of the line will no longer be visible (even with `sidescrolloff=0`). If you do use `vert resize 30` after switching windows, the beginning of the line *will* be visible until you switch to that window (then vim will adjust the window to show your cursor).

And (what I think is your actual problem), using `vert resize 80` after switching to the small window doesn't make the beginning of the line visible even though there's room for it.

Since it's an enhancment and not a bug and it's not pressing for you, I'm closing. Thanks for following up!

**Closed by idbrii** 2017-01-11 00:25 UTC
